# Generated by Django 4.0.3 on 2022-04-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhome', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='picture',
            field=models.ImageField(null=True, upload_to='tourImages'),
        ),
    ]
