# Generated by Django 4.0.3 on 2022-04-11 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myhome', '0003_visitplaces'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitplaces',
            name='place_pic',
        ),
        migrations.AddField(
            model_name='visitplaces',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='visitplaces',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myhome.tourpackage'),
        ),
        migrations.AddField(
            model_name='visitplaces',
            name='picture',
            field=models.ImageField(null=True, upload_to='placeImages'),
        ),
    ]
